# -*- coding: utf-8 -*-
"""faedetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AFFghiN6d6CCBfA6iUakyE4dKE_7_GT
"""

!pip install opencv-python-headless
import cv2  # Main library for computer vision tasks
import matplotlib.pyplot as plt  # Used to display images
from google.colab import files  # To upload files from your computer
import numpy as np  # To work with image arrays (optional)
from PIL import Image  # To handle image files easily

uploaded = files.upload()
# Load the first image from the uploaded files
for fn in uploaded.keys():
    img_path = fn  # Save the filename
    img = cv2.imread(img_path)  # Read the image using OpenCV
    break  # Only use the first image for now
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(8, 6))  # Set the image size
plt.imshow(img_rgb)  # Show the image
plt.axis('off')  # Hide axes and ticks
plt.title("Detected Faces")  # Title of the image
plt.show()  # Display the image